### ISSUE TITLE
Bastion host in same account as the Lambda Function

### ISSUE THREAD

**Issue by Nr18** [Netflix/bless#23]
Is this setup aimed to have the bastion in the same account as the lambda function or do you only use the aws account for the KMS key and lambda function?

**Comment by russell-lewis** [comment]
Our recommendation is that the lambda function exist in its own AWS account, isolated from the rest of your infrastructure, and with a minimal set of people who can access it.

This can help you better protect the KMS key wrapping your CA Keys, the CA Keys, the lambda code and configurations, and the audit trail left behind in CloudWatch Logs.

You can configure the BLESS Lambda to only allow the function to be called with the credentials for the IAM Role assigned to your bastions (even in a different AWS account).  This means you still have to protect those bastion credentials from misuse.

For development/testing, I'd also recommend you can stand up a test BLESS lambda function in a more accessible account.  The test environment should have no access to the real KMS key or CA key values, and you shouldn't have any services that trust the test CA key.

**Comment by Nr18** [comment]
Great thanks for the information!
