### ISSUE TITLE
Restrict users from jumping to certain hosts

### ISSUE THREAD

**Issue by Nr18** [Netflix/bless#24]
At what point would you recommend that you restrict or even better whitelist the hosts that a certain user is allowed to connect to?

In my opinion that would be the bastion itself right? But is a bastion per group of users the way to go or add some business logic to the script that will handle the signing of the SSH Certificate?

Thanks

**Comment by russell-lewis** [comment]
Authorization decisions are out of scope for BLESS right now, as it currently has no user authentication mechanisms included.  Therefore the authorization decisions must be made prior to requesting a certificate for a user.
