### ISSUE TITLE
Question about existing user groups?

### ISSUE THREAD

**Issue by jsrichards** [Netflix/bless#26]
Is there a user group I can ask this question too? "Does BLESS provision both private and public keys, or does the user provide a public key/cert to be signed?"

**Comment by russell-lewis** [comment]
You can use https://gitter.im/Netflix/bless for questions and discussions.

BLESS uses a private key for CA purposes that it must keep protected.  You must provisioned manually, when you deploy the function.  Your instances trust that CA's public key, enabling certificates issued by BLESS to authenticate users.  BLESS signs SSH Certificate requests with that CA private key.

For us, the "BLESS clients" are our SSH bastions.  The client is responsible for protecting the AWS credentials required to invoke BLESS.  Anyone with those AWS credentials can call BLESS, and request certificates.  For starters, you can use iptables to restrict SSH bastion users from accessing the AWS credentials directly via the Instance Metadata endpoint.

Clients make requests to BLESS to issue an SSH Certificate.  That request contains the public key associated with the private the client will be using to authenticate into an instance.  BLESS never needs access to the client's private key.  The client is responsible for generating and protecting the private key.  You can, and I'd recommend, using ephemeral RSA key pairs in addition to certificates.  Thereby linking one client private key and one SSH certificate, and restricting the certificate to only be valid from one IP to one target, for a few minutes.

I hope that answers your question, but feel free to use our gitter channel.

**Comment by jsrichards** [comment]
Thank you for the response, very helpful!
