### ISSUE TITLE
Changed expected location of ca.pem

### ISSUE THREAD

**Issue by diasjorge** [Netflix/bless#48]
When this commit got merged 62fe7fcd78c901957c1ceb79e410ca72e668864d the location of the ca.pem file is no longer being read from the root of the projects (where the publish command places it) but now it's expected to be inside /config directory.

I don't know if this behaviour is intended (so we should change the makefile publish) or just a side effect and should be fixed.

I could help with it and provide a fix but I'd like to know what do you think.

**Comment by russell-lewis** [comment]
Good catch, that's a bug.  I'll get a fix out for this.

**Comment by russell-lewis** [comment]
Merged https://github.com/Netflix/bless/pull/50
