### ISSUE TITLE
Submit compiled lambda dependencies to lambda-packages

### ISSUE THREAD

**Issue by Miserlou** [Netflix/bless#5]
Hey team! Great project!

Rather than providing instructions on how to compile the necessary dependencies on EC2, it'd be much more useful for everybody if you could submit the compiled resources to [lambda-packages](https://github.com/Miserlou/lambda-packages). That way, other projects can all benefit from the work that you've done, and BLESS's users won't have to manually compile their own resources.

Thoughts?

**Comment by russell-lewis** [comment]
Looks like a good thing to me, I'll take a closer look at this soon.

**Comment by russell-lewis** [comment]
After taking a look at this, it doesn't sound like something we'd want to use.  A large package of binaries built by another party that aren't signed and verified isn't something we want to pull into such a critical service.
