### ISSUE TITLE
Unable to login with the cert got from lambda function

### ISSUE THREAD

**Issue by shanmukha1499** [Netflix/bless#83]
I am getting "Authentication tried for user with valid certificate but not from a permitted host (ip=x.x.x.x)." in /var/log/auth.log on the bastion server and unable to login what can be the problem?

**Comment by russell-lewis** [comment]
You need to set the bastion_ips to match which IP(s) you will use to connect to the instance.

https://github.com/Netflix/bless/blob/master/bless/request/bless_request.py#L141-L142

From man ssh-keygen
             source-address=address_list
                     Restrict the source addresses from which the certificate is considered valid.  The address_list is a comma-separated list of one or more address/net-
                     mask pairs in CIDR format.
