### ISSUE TITLE
make test fails on deprecated warnings [linting]

### ISSUE THREAD

**Issue by MNibble** [Netflix/bless#84]
(venv) ubuntu@hostname$ make test
--> Linting Python files
PYFLAKES_NODOCTEST=1 flake8 bless
bless/config/bless_config.py:188:10: W605 invalid escape sequence '\W'
bless/config/bless_config.py:188:10: W605 invalid escape sequence '\W'
bless/request/bless_request.py:19:23: W605 invalid escape sequence '\Z'
bless/request/bless_request.py:27:2: W605 invalid escape sequence '\A'
bless/request/bless_request.py:27:14: W605 invalid escape sequence '\s'
bless/request/bless_request.py:27:18: W605 invalid escape sequence '\Z'
make: *** [lint] Error 1
(venv) ubuntu@hostname$ vim Makefile 
(venv) ubuntu@hostname$ make test
--> Linting Python files

**How to reproduce:**

docker run -it ubuntu:18.04 /bin/bash
apt update 
apt install git make python3.6 python3-venv 
git clone https://@github.com/Netflix/bless.git
cd bless
python3.6 -m venv venv
source venv/bin/activate
make develop
make test

**Comment by ozbillwang** [comment]
Yes, I saw the same issue.

@MNibble 

To improve the codes you run with, maybe you can directly run with official `python:3` image

```
docker run -ti --rm python:3 bash
root@24e69bb98324:/# git clone https://@github.com/Netflix/bless.git
root@24e69bb98324:/bless# python -m venv venv
root@24e69bb98324:/bless# source venv/bin/activate
(venv) root@24e69bb98324:/bless# make develop
(venv) root@24e69bb98324:/bless# make test
--> Linting Python files
PYFLAKES_NODOCTEST=1 flake8 bless
bless/config/bless_config.py:188:10: W605 invalid escape sequence '\W'
bless/config/bless_config.py:188:10: W605 invalid escape sequence '\W'
bless/request/bless_request.py:19:23: W605 invalid escape sequence '\Z'
bless/request/bless_request.py:27:2: W605 invalid escape sequence '\A'
bless/request/bless_request.py:27:14: W605 invalid escape sequence '\s'
bless/request/bless_request.py:27:18: W605 invalid escape sequence '\Z'
Makefile:22: recipe for target 'lint' failed
make: *** [lint] Error 1
```

**Comment by ozbillwang** [comment]
and this is the related issue: https://github.com/PyCQA/pycodestyle/issues/755

**Comment by ozbillwang** [comment]
Ok, we should seems to ignore this test feature currently

There are too much lint errors with `flake8`, even I ignore `W605`

**Comment by ozbillwang** [comment]
release `0.2.0` works, it is based on python 2.7

the upgrade to python 3.6 is broken in release `0.3.0`

**Comment by russell-lewis** [comment]
This should be resolved with the code after https://github.com/Netflix/bless/commit/5d92a03d39ab08a71657bdf35dd55d4c1d3a828f
